### ISSUE TITLE
Regression caused by using resolve_or_missing out of context class

### ISSUE THREAD

**Issue by majkls23** [pallets/jinja#677] opened 2017-02-02 06:28 UTC
Due to usage of resolve_or_missing() out of Context class I have to rewrite my custom context class. This function is undocumented so please remove its ussage from external code or update documentation. I spend three hours by finding why my custom class code failing.

Thanks.

**Comment by ThiefMaster** [comment] 2017-02-02 10:03
Possible duplicate of #675?

**Closed** 2017-02-02 13:03 UTC

**Comment by majkls23** [comment] 2017-02-03 07:44
After upgade to 2.9.5 issue disappeared. Version 2.8 is also ok. I am sending code only for clarification On 2.9.4 i got following backtrace:

``
Traceback (most recent call last):
  File "X:\sw-jachym\gui\PrasnostPanel.py", line 288, in GenerovatReport
    render(sablona, "mereniPrasnost_mereni#"+str(id), dlg2.GetPath())
  File "X:\sw-jachym\lib\sablonator.py", line 332, in render
    t.render(d, jinja_env)
  File "C:\Python27\lib\site-packages\docxtpl\__init__.py", line 123, in render
    xml = self.build_xml(context,jinja_env)
  File "C:\Python27\lib\site-packages\docxtpl\__init__.py", line 88, in build_xml
    xml = self.render_xml(xml, context, jinja_env)
  File "C:\Python27\lib\site-packages\docxtpl\__init__.py", line 81, in render_xml
    dst_xml = template.render(context)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'mereniPrasnost_lokace' is undefined


Code:

```python
class ContextDictator(Context):
	def __init__(self, environment, parent, name, blocks):
		self.debug = False
		Context.__init__(self, environment, parent, name, blocks)
		# soukrome promenne, ktere jsou dynamicky nacitany z DB
		self.table = None
		if self.debug: print "ContextDictator.__init__()"

	def resolve(self, key):
		if self.debug: print "resolve()"
		if key in self.vars:
			return self.vars[key]
		if key in self.parent:
			return self.parent[key]
		try:
			return self.environment.dictator[key]
		except Exception, e:
			print e
			return self.environment.undefined(name=key)
	
	def get(self, key, default = None):
		if self.debug: print "get()"
		try:
			return self[key]
		except KeyError:
			try:
				return self.environment.dictator[key]
			except Exception, e:
				if self.debug: print e
				return default
	
	def __contains__(self, name):
		if name in self.vars or name in self.parent:
			return True
		else:
			try:
				self.environment.dictator[name]
			except Exception, e:
				if self.debug: print e
				return False
			else:
				return True
         
def render(template, dictator_init_string, output_file):
	d = Dictator(None, dictator_init_string)
	t = DocxTemplate(template)
	f = Filters(conn = d.conn, tmpl = t)
		
	jinja_env = jinja2.Environment()
	# definujeme spojeni pro DB
	jinja_env.dictator = d
	jinja_env.context_class = ContextDictator

	f.apply(jinja_env)

	t.render(d, jinja_env)
	t.save(output_file)
