### ISSUE TITLE
Provide meta.find_undeclared_variables() behavior from Jinja2 2.10

### ISSUE THREAD

**Issue by captainmalloc** [pallets/jinja#1668] opened 2022-05-31 17:41 UTC
Jinja2 2.11.0 introduced a change in the `find_undeclared_variables()` behavior returning only the subset of variables the are not available in the environment globals as described in https://github.com/pallets/jinja/issues/931 and https://github.com/pallets/jinja/pull/994

Before the fix it was easy to get all the variables referenced in the template using `meta.find_undeclared_variables(ast)` or all the variables referenced in the template but not defined in the environment using `meta.find_undeclared_variables(parsed) - env.globals.keys()`.
Now only the first use-case can be satisfied using the API.
I propose to introduce a new function to restore the functionality proposed in the second scenario, such as `meta.find_referenced_variables(ast)`

**Comment by davidism** [comment] 2022-05-31 18:08
Duplicate of https://github.com/pallets/jinja/issues/1580

**Closed** 2022-05-31 23:19 UTC
