### ISSUE TITLE
Bug in jinja2.loaders: split_template_path using hardcoded '/'

### ISSUE THREAD

**Issue by eddieparker** [pallets/jinja#411] opened 2015-02-23 21:21 UTC
On line 27, there's a line that does:

for piece in template.split('/'):

This breaks on Windows if I'm feeding it a windows path ("C:\\Foo\\Bar\\baz").  Switching it to path.sep seems to do the trick, and should keep the 'NIXes happy.

**Comment by jeffwidman** [comment] 2016-04-13 09:24
Direct link to relevant code: https://github.com/pallets/jinja/blob/master/jinja2/loaders.py#L27

**Comment by ColdHeat** [comment] 2016-07-06 05:29
I'm also affected by this and it took some time to nail down the issue. 

It doesn't seem intuitive that FileSystemLoader would not respect the differences in filesystems between operating systems. It makes more sense to use `os.path.join` (which will result in `\\` on Windows) instead of `"/".join()`. 

If this is as intended and is a definite wont fix can we be more clear about what is the actual issue instead of `TemplateNotFound` since under normal conditions Python would find the template?

**Comment by davidism** [comment] 2016-07-06 06:04
Jinja template paths are not filesystem paths.  #412

**Closed by davidism** 2016-07-06 06:04 UTC

**Comment by ColdHeat** [comment] 2016-07-06 07:29
In that case, it would seem to me that FileSystemLoader should be loading off of a file system path instead of a template path. 

And I don't understand how increasing my consistency would help Python do the right thing when [the affected code](https://github.com/isislab/CTFd/commit/d853da2b7f98edb184878f79f8d9714fb6dbc179) uses `os.path.join` which will use `os.sep` which on Windows will output `\\`.

**Comment by ThiefMaster** [comment] 2016-07-06 07:31
FileSystemLoader loads the templates from a file system, but template paths within Jinja are not filesystems paths even if they end up getting mapped to one.
