### ISSUE TITLE
Add ability to pass filename for Environment.from_string function

### ISSUE THREAD

**Issue by xahon** [pallets/jinja#1686] opened 2022-07-21 10:25 UTC
I'd like to pass additional debug info into that function. I use some kind of preprocessing and lines will shift but at least the file will be known in traceback report. But if you don't use any kind of preprocessing you still can interface filesystem in your system and you want to give the user know which file has a template error

**Comment by davidism** [comment] 2022-07-21 15:01
Duplicate of https://github.com/pallets/jinja/issues/1316

**Closed by davidism** 2022-07-21 15:01 UTC
