### ISSUE TITLE
AttributeError in method call treated as UndefinedError in template

### ISSUE THREAD

**Issue by cfrademan** [pallets/jinja#854] opened 2018-05-16 11:30 UTC
https://github.com/pallets/jinja/blob/a7ba0b637805c53d442e975e3864d3ea38d8743f/jinja2/environment.py#L427-L438

If I call a method that raises an `AttributeError`, Jinja's attribute access logic treats it as a missing attribute on the object, rather than an error raised inside the method, and returns an `UndefinedError`.

```python
class Thing:
    def break_stuff(self):
        raise AttributeError()
```

```
{{ thing.break_stuff() }}
```

```
jinja2.exceptions.UndefinedError: 'dude' has no attribute 'lets_break_sum_stuff'
```

The error reported should be the `AttributeError` raised in the method, since it was not related to attribute access in the template.

I have no idea, how to fix this without a performance impact of some sort while handling errors. Perhaps we need to attach the original exception content instead of formatting a new error message?

**Comment by ThiefMaster** [comment] 2018-05-16 11:47
Yeah, swallowing AttributeErrors originating from inside other code bit me in the ass in the past as well. I also don't see a decent solution for it. Inspecting the traceback would be an option, but the overhead would probably still be too big since handling and catching AttributeErrors is very common in Jinja - people generally use `foo.bar` to access dict elements in Jinja, so the first AttributeError would always result in this code to run.

**Comment by cfrademan** [comment] 2018-05-16 11:59
Well it seems, I am yet to confirm that given the above scenario, I didnt see the source of the problem in the trackback. I am guessing, yet to look that that error is raised from None or something. I guess I will look into this more myself.

**Comment by davidism** [comment] 2019-10-28 16:58
I can't reproduce this issue with the given example. A method that exists but raises an `AttributeError` results in an `AttributeError` when called. The way `Environment.getattr` works *would* mask `@property` attributes that raise `AttributeError`, but I'm fairly sure there's some Python docs out there already telling you not to do that. ;-)

Given that there's no way around this besides looking at frames, which is slow and possibly not portable, closing this.

**Closed by davidism** 2019-10-28 16:58 UTC
