### ISSUE TITLE
Import error in Jinja 2.10.x/2.11.x

### ISSUE THREAD

**Issue by Nathanmalnoury** [pallets/jinja#1594] opened 2022-02-18 15:02 UTC
Jinja 2.10.x installs the latest update of Markupsafe [2.1.0](https://markupsafe.palletsprojects.com/en/2.1.x/changes/#version-2-1-0) released yesterday, which resolves in an ImportError.

This seems to be caused by the removal of `soft_unicode` from markupsafe in that version.

How to replicate: 

In a terminal: 
```shell
$ pip install Jinja2~=2.10.3 # same result with 2.11.x
$ python -c "import jinja2"
```

Traceback: 
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nathan/Project/jinja-bug/venv/lib/python3.8/site-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/home/nathan/Project/jinja-bug/venv/lib/python3.8/site-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/home/nathan/Project/jinja-bug/venv/lib/python3.8/site-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/home/nathan/Project/jinja-bug/venv/lib/python3.8/site-packages/jinja2/utils.py", line 642, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/nathan/Project/jinja-bug/venv/lib/python3.8/site-packages/markupsafe/__init__.py)
```

Note:

Installing the last MarkupSafe version before 2.1.0 fixes this issue:
```shell
$ pip install MarkupSafe~=2.0.0
$ pip install Jinja2~=2.10.3 
$ python -c "import jinja2"  # works
```

Environment:

- Python version: 3.8.10
- Jinja version: 2.10.x / 2.11.x

**Comment by davidism** [comment] 2022-02-18 15:09
Duplicate of #1585 

You are using an unsupported version of Jinja, please update to the latest version if possible. Additionally, please read https://hynek.me/articles/semver-will-not-save-you/, then use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of these types of changes early.

**Closed by davidism** 2022-02-18 15:09 UTC

**Comment by vpogrebi** [comment] 2022-02-18 16:12
Sorry... it's not clear from the comments - is this fix (to replace 'soft_unicode' with 'soft_str') coming? How soon?
