### ISSUE TITLE
loop with conditions should be fully aware of filters in loop.length etc methods

### ISSUE THREAD

**Issue by i00** [pallets/jinja#1078] opened 2019-10-11 02:55 UTC
I have also posted this bug here:
https://github.com/home-assistant/home-assistant/issues/27435

---

## Expected Behavior
Looping through a set and calling loop.length should list the length within the filtered list

## Actual Behavior
The loop.length reports the filtered list length only up to the first "and"

## Template Code
```jinja
{% for state in states.sensor if 'seventeentrack_package_' in state.entity_id and state.state == 'Ready to be Picked Up' -%}{% if loop.first %}You have {{loop.length}} packages ready to pick up: {% else %}, {% endif %}{{state.name}}{% endfor %}
```
The result is: "You have 2 packages ready to pick up: Sense Energy Monitor"
I have 2 packages, of which only 1 is waiting to be picked up ... I have hundreds of sensors, so the first condition is working.

## Your Environment
Home Assistant (Docker image 0.99.3)
https://hub.docker.com/r/homeassistant/home-assistant/

**Comment by davidism** [comment] 2019-10-11 14:47
This is a bug with `loop.length`, not with multiple conditions. The following template demonstrates the length working with two conditions, but changing the loop to be only one item long produces a count of two. Fairly sure this is a duplicate of #751 and #794.

```
{% for i in range(10) if i is odd and i < 8 %}
{{ i }} / {{ loop.length }}
{% endfor %}
```

```
1 / 4
3 / 4
5 / 4
7 / 4
```

**Closed by davidism** 2019-10-11 14:47 UTC

**Comment by i00** [comment] 2019-10-11 15:30
> This is a bug with loop.length, not with multiple conditions. 
Ahh just assumed that the 2nd condition was not being considered in .Length since I had 2 items in the list if the 2nd condition wasn't there :P
