### ISSUE TITLE
Update to 

### ISSUE THREAD

**Issue by feede7** [pallets/jinja#1597] opened 2022-02-18 18:08 UTC
I think that this release broke the use of jinja2!

![image](https://user-images.githubusercontent.com/22085131/154737675-88d831c6-62f4-4f03-9fff-f226209ea572.png)

```
 venv/lib/python3.7/site-packages/amaranth/build/plat.py:6: in <module>
     import jinja2
 venv/lib/python3.7/site-packages/jinja2/__init__.py:12: in <module>
     from .environment import Environment
 venv/lib/python3.7/site-packages/jinja2/environment.py:25: in <module>
     from .defaults import BLOCK_END_STRING
 venv/lib/python3.7/site-packages/jinja2/defaults.py:3: in <module>
     from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
 venv/lib/python3.7/site-packages/jinja2/filters.py:13: in <module>
     from markupsafe import soft_unicode
 E   ImportError: cannot import name 'soft_unicode' from 'markupsafe' 
```

Environment:

- Python version: `python3.7`
- Jinja version: `Jinja2-2.11.3`

**Comment by ThiefMaster** [comment] 2022-02-18 18:10
Duplicate of #1585 

You are using an unsupported version of Jinja, please update to the latest version if possible. Additionally, please read https://hynek.me/articles/semver-will-not-save-you/, then use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of these types of changes early.

**Closed** 2022-02-18 18:09 UTC
