### ISSUE TITLE
Nonstandard operator precedence

### ISSUE THREAD

**Issue by ngaya-ll** [pallets/jinja#508] opened 2015-10-28 21:26 UTC
In most programming languages, operators are grouped into families having equal precedence.  In Jinja2's parser, each operator has its own precedence level.  This affects the associativity of some expressions.

For example, in Python and Java, `*`,`/`, `//`, and `%` all have the same precedence.  In Jinja2, these operators have different precedence.  This means that a given expression may yield different results from expected when evaluated in a Jinja2 template (see example).  Jinja2 should follow the common convention to avoid "gotchas" and unintuitive behavior.

Python's operator precedence is documented [here](https://docs.python.org/2/reference/expressions.html#operator-precedence).  Java's operator precedence is described [here](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/operators.html).

**Example:**

    {{ 10 * 1 // 2 }}

**Expected result:**

    5

**Actual result:**

    0

**Comment by jeffwidman** [comment] 2016-04-13 05:56
Dupe of #119

**Closed by jeffwidman** 2016-04-13 05:56 UTC
