### ISSUE TITLE
jinja2 variable won't update in a loop based on operation performed as expected

### ISSUE THREAD

**Issue by sadaf2605** [pallets/jinja#697] opened 2017-03-28 05:51 UTC
I am setting jinja2 variable outside (before) the loop, yet it is being resetted every time the loop is being iterated.
Also asked at stackoverflow: http://stackoverflow.com/questions/43061439/jinja2-variable-wont-update-in-a-loop-based-on-operation-performed-as-expected
I have this following code:

        {% set c = 0 %}
        {% for n in n_list %}

          {% if loop.index % 3 == 0 %}

          {% else %}
              {% set l = range(3, 6) | random %}
                {% set c = c+l %}
          {% endif %}

          {{ loop.index }} {{c}} {{l}}<br>

        {% endfor %}
---

## Expected Behavior
1 3 3
2 7 4
2 7 0
2 11 4
...
## Actual Behavior
1 3 3
2 4 4 
3 0  
4 4 4 
5 5 5 # ...
6 0 
7 5 5
8 5 5
9 0 
10 4 4

## Template Code
```
        {% set c = 0 %}
        {% for n in n_list %}

          {% if loop.index % 3 == 0 %}

          {% else %}
              {% set l = range(3, 6) | random %}
                {% set c = c+l %}
          {% endif %}

          {{ loop.index }} {{c}} {{l}}<br>

        {% endfor %}
```

## Your Environment
* Python version: 3.6.0
* Jinja version: 2.9.5

**Comment by ThiefMaster** [comment] 2017-03-28 06:15
Duplicate of #641

**Closed by ThiefMaster** 2017-03-28 06:15 UTC

**Comment by zhangguanzhang** [comment] 2020-08-02 10:45
use map
```yaml
- set_fact: 
    docker_version: |-
      {%- set docker_version_list= temp_var.results | map(attribute='version') | list | select('search', docker.version ) | list  -%}
      {%- if docker_version_list | length == 1 -%}{{docker_version_list[0]}}
      {%- else -%}
        {%- set vmax = {'max': docker.version + '.0'} -%}
        {%- for ver in docker_version_list -%}
          {%- if vmax['max'] is version(ver, '<') -%}
            {%- set _ = vmax.update({"max": ver}) -%}
          {%- endif -%}
        {%- endfor -%}
        {{ vmax['max'] }}
      {%- endif %}
```
