### ISSUE TITLE
PackageLoader gives misleading error when wrong path given

### ISSUE THREAD

**Issue by Dreamsorcerer** [pallets/jinja#1725] opened 2022-09-25 16:19 UTC
Just spent 10 minutes trying to debug this error:
```
ValueError: The 'my_app' package was not installed in a way that PackageLoader understands.
```

The package is absolutely fine. I just set the path to a non-existing path, so this code was never run:
https://github.com/pallets/jinja/blob/main/src/jinja2/loaders.py#L318-L320

Maybe add an `else` to the `for` which raises a different error?

Or that piece of code could be simplified down to something like:
```
try:
    template_root = next(p for root in roots if os.path.isdir(p := os.path.join(root, package_path)))
except StopIteration:
    raise ValueError(f"Template path not found in package: {package_path}.")
```
Or if you convert everything to `Path`, that can be simplified to `next(p for root in roots if (p := root / package_path).is_dir())`.

**Comment by davidism** [comment] 2022-09-26 19:37
Duplicate of #1705

**Closed by davidism** 2022-09-26 19:37 UTC

**Comment by Dreamsorcerer** [comment] 2022-09-26 20:07
Ah, thanks, missed that one.

For a PR, would the `else` be the desired change, or would the suggested refactor be good (I note that it does use the controversial walrus operator)?

**Comment by davidism** [comment] 2022-09-26 20:08
There's already an open PR linked to that issue.

**Comment by Dreamsorcerer** [comment] 2022-09-26 20:10
OK, I think it's wrong though. Will leave some feedback.
