### ISSUE TITLE
Please fix current version documentation sidebar for jinja2  

### ISSUE THREAD

**Issue by pete312** [pallets/jinja#1834] opened 2023-04-07 15:48 UTC
Issue number [#1768 ](https://github.com/pallets/jinja/issues/1768 ) is showing complete, but it looks like the issue is still ongoing even in latest https://jinja.palletsprojects.com/en/latest/api/

I believe (not sure) that I saw latest at one time got fixed but it must have reverted since.  However, I never saw v3.1 fixed.  The fix should be applied to all versions if possible as they are important ongoing development.

**Comment by davidism** [comment] 2023-04-07 16:02
Duplicate of way more of these

**Closed by davidism** 2023-04-07 16:02 UTC
