### ISSUE TITLE
markupsafe version 2.1.0 removed 'soft_unicode' function

### ISSUE THREAD

**Issue by vikingUnet** [pallets/jinja#1600] opened 2022-02-21 11:45 UTC
Hello!
Today we have a big problem with installing requirement dependency as markupsafe >= 0.23
https://github.com/pallets/jinja/blob/737a4cd41d09878e7e6c584a2062f5853dc30150/setup.py#L53
and we forced to installversion markupsafe==2.0.1 in handly mode.
Please, change this dependency for backward compatibility,
problam describe at this link https://githubhot.com/repo/pallets/markupsafe/issues/284
Thanks!!!

**Comment by ThiefMaster** [comment] 2022-02-21 11:48
https://github.com/pallets/jinja/issues/1585

**Comment by davidism** [comment] 2022-02-21 11:48
Duplicate of #1585 

You are using an unsupported version of Jinja, please update to the latest version if possible. Additionally, please read https://hynek.me/articles/semver-will-not-save-you/, then use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of these types of changes early.

**Closed** 2022-02-21 11:48 UTC
