### ISSUE TITLE
method open_if_exists raises exception, instead of returning None

### ISSUE THREAD

**Issue by Boberro** [pallets/jinja#399] opened 2015-01-21 15:03 UTC
According to description, method open_if_exists instead of raising exception should return None.

https://github.com/mitsuhiko/jinja2/blob/master/jinja2/utils.py#L146

EDIT: Forgot to specify - happens only on windows.

**Comment by ThiefMaster** [comment] 2015-02-06 00:30
Which exception are you getting? I just tested it with a missing file in the first search path on Windows and the `FileNotFoundError` is a subclass of `IOError` and properly caught.

Was it a folder you didn't have access to by any chance? In that case I'd actually expect an exception because unlike a template not being found in one of the search paths, an inaccessible search path is most likely not intended.

**Comment by edouardklein** [comment] 2016-08-02 07:41
Hi !

This bug in flask_restplus:
https://github.com/noirbizarre/flask-restplus/issues/187

is triggered by open_if_exists raising a NotADirectoryError instead of returning None.

I do not know both codebases enough to have an opinion on whether this is the intended, correct or expected behavior or not, although I lean to the side of this being a bug in Jinja2, as the per the principle of least surprise, I'd have expected the function to return None when the directory that open_if_exists' argument supposedly is in does not exist.


I will submit a pull request correcting this behavior, If your opinion is that raising the exception is the correct behavior instead, then maybe an update of the documentation is in order, as flask is one non trivial example of client code that expected the 'return None' behavior.

**Comment by davidism** [comment] 2017-10-31 20:03
I closed the PR linked above because the case was invalid.

Given that there haven't been any other examples of this failing, I'm closing this.

**Closed by davidism** 2017-10-31 20:03 UTC

**Comment by tsopokis** [comment] 2018-11-07 18:48
I had the same issue when bundling the flask app in a pex file. ignoring ENOTDIR works as expected
