### ISSUE TITLE
Can not set default value to 0 in make_attrgetter

### ISSUE THREAD

**Issue by lisongmin** [pallets/jinja#1358] opened 2021-02-23 05:03 UTC
Hi,

When I add default parameter to `groupby` filter locally, I just found that `make_attrgetter` ignore the default value 0.

`make_attrgetter` should allow setting the default value to 0, False, [] etc.

I can send a PR if you agree with it.

thanks.

**Comment by davidism** [comment] 2021-02-23 05:07
Duplicate of #1331

**Closed** 2021-02-23 05:07 UTC
