### ISSUE TITLE
jinja2.exceptions.TemplateSyntaxError can't be unpickled

### ISSUE THREAD

**Issue by ttencate** [pallets/jinja#1129] opened 2020-01-20 11:57 UTC
```python
>>> import jinja2
>>> import pickle
>>> try:
...   jinja2.Template('{{')
... except jinja2.exceptions.TemplateSyntaxError as e:
...   ex = e
...
>>> p = pickle.dumps(ex)
>>> pickle.loads(p)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() missing 1 required positional argument: 'lineno'
```

Why should we care about pickling exceptions? Well, the `multiprocessing` module uses pickling to send them across thread boundaries.

It's also rather hard to debug: if a multiprocessing task raises this Jinja error, `multiprocessing` raises the above unpickling error without any indication that it's related to Jinja at all. I had to un-parallelize my code to get a proper stack trace to show up for this one.

## Your Environment
* Python version: 3.5.9, 3.8.1
* Jinja version: 2.10.3

**Comment by davidism** [comment] 2020-01-20 13:04
Duplicate of #1117

**Closed by davidism** 2020-01-20 13:04 UTC

**Comment by ttencate** [comment] 2020-01-20 15:55
Thanks! I searched issues, but not PRs.
