### ISSUE TITLE
Strange variable scope with extends and includ

### ISSUE THREAD

**Issue by roba91** [pallets/jinja#546] opened 2016-02-18 10:16 UTC
Here is the setup:

test_include.html :

``` html
<p>Var: {{ var }}</p>
```

test_base.html :

``` html
<html>
<head>
  <title>Test</title>
</head>
<body>
  <h1>Test</h1>
  {% include 'test_include.html' %}
</body>
</html>
```

test.html :

``` html
{% extends 'test_base.html' %}

{% set var = 'foobar' %}
```

This results in a page that looks like:

``` html
...
<h1>Test</h1>
<p>Var: </p>
...
```

So var is not accessible in the include.
But if you add something like `{{var}}` or `{% if var %}{% endif %}` to test_base.html the result looks like:

``` html
...
<h1>Test</h1>
<p>Var: foobar</p>
...
```

So just by accessing var in test_base (no matter if before or after the include) var is also accessible within test_include.

**Comment by bennettrogers** [comment] 2016-07-14 04:08
I just ran into this issue as well. I'm trying to implement the "active_page" setup from the Jinja [tips and tricks](http://jinja.pocoo.org/docs/dev/tricks/) section, using a nav declared inside my `header.html` that gets included inside `layout.html`. The `active_page` variable is set in a child template. Basically, the setup is exactly what @roba91 describes.

Is there a reason the variable declared in the child template isn't accessible in the include? The statement that "assignments outside of blocks in child templates are global and executed before the layout template is evaluated" would make me think this should work.

For now I'm going to hack around it by putting `{% if active_page %}{% endif %}` in my layout.html (thanks for that tip @roba91).

**Comment by mitsuhiko** [comment] 2017-01-07 14:26
Duplicate of #603

**Closed by mitsuhiko** 2017-01-07 14:26 UTC
