### ISSUE TITLE
Macros with native types convert text that looks like a Python object to a Python object

### ISSUE THREAD

**Issue by felixfontein** [pallets/jinja#1676] opened 2022-06-24 12:01 UTC
With ansible-core 2.13, which uses `NativeEnvironment`, I noticed that macros convert text that looks like a Python object into actual Python objects. This happened to me in a template that was constructing a JSON file; a macro in it generated a JSON object, which was suddenly converted from text to a Python dictionary, and then converted back to text, resulting in invalid JSON (it was using the wrong quotation marks).

Ref: https://github.com/ansible/ansible/issues/78141

This seems to be a bug in Jinja2, as it can be easily reproduced as follows:
```
>>> from jinja2.nativetypes import NativeEnvironment
>>> NativeEnvironment().from_string('{% macro foo() %}{ "foo": "bar" }{% endmacro %}Test: {{ foo() }}').render()
"Test: {'foo': 'bar'}"
```
The result should have been
```
'Test: {"foo": "bar"}'
```
with double quotation marks inside the string, instead of single quotation marks.

I'm using jinja2 3.1.2.

CC @mkrizek

**Comment by davidism** [comment] 2022-06-24 12:42
Duplicate of https://github.com/pallets/jinja/issues/917

**Closed by davidism** 2022-06-24 12:42 UTC
