### ISSUE TITLE
yield inside async function requires Python >= 3.6

### ISSUE THREAD

**Issue by p1otr** [pallets/jinja#655] opened 2017-01-10 19:55 UTC
Dunno if it was intended but jinja2 now requires Python >= 3.6 due to line 24 in jinja2/asyncfilters.py and 35 in jinja2/asyncsupport.py.

Since next Debian stable will have Python 3.5 and jinja2 still declares 3.5 as supported, could you workaround this in async_select_or_reject() and generate_async()?

## Full Traceback
```pytb
$ python3.5 -m py_compile jinja2/asyncfilters.py jinja2/asyncsupport.py                                                                                                                             
  File "jinja2/asyncfilters.py", line 24
    yield item
    ^
SyntaxError: 'yield' inside async function

  File "jinja2/asyncsupport.py", line 35
    yield event
    ^
SyntaxError: 'yield' inside async function
```

## Your Environment
* Python version: 3.5
* Jinja version: 2.9.4

**Comment by ThiefMaster** [comment] 2017-01-10 19:56
No, it doesn't. It only fails when you try to compile all files - including files that would never be imported in older Python versions. Duplicate of #643. Also see #653

**Closed by ThiefMaster** 2017-01-10 19:56 UTC

**Comment by ThiefMaster** [comment] 2017-01-10 19:58
Assuming you are building a .deb, you could probably simply remove these two files prior to compiling when installing it for Python<3.6

**Comment by ThiefMaster** [comment] 2017-01-10 19:59
Actually, it seems that compilation of all other files still succeeds, so you can silently ignore these errors.

**Comment by thijstriemstra** [comment] 2017-01-25 20:57
Getting the same error with Python 3.5.2 and pyqtdeploy (5.7):

```
pyqtdeploycli: Unable to freeze files: Traceback (most recent call last):
  File "/tmp/qt_temp-LVGpmS/freeze.py", line 104, in <module>
    freeze_as_data(py_filename, out_filename, embedded_name)
  File "/tmp/qt_temp-LVGpmS/freeze.py", line 36, in freeze_as_data
    code = _get_marshalled_code(py_filename, embedded_name)
  File "/tmp/qt_temp-LVGpmS/freeze.py", line 77, in _get_marshalled_code
    co = compile(source, embedded_name, 'exec')
  File ":/jinja2/asyncfilters.py", line 24
SyntaxError: 'yield' inside async function
```

Will exclude the files as suggested.
