### ISSUE TITLE
Extra whitespace in output when macro ends with an if statement

### ISSUE THREAD

**Issue by adambousley** [pallets/jinja#972] opened 2019-04-25 19:26 UTC
Running with trim_blocks=True and lstrip_blocks=True, whitespace from if statements is usually removed. Seems to generally works as expected, except in cases where a macro ends with an if statement

## Expected Behavior
No blank line when macro ends with an if statement and trim_blocks=True

## Actual Behavior
Extra blank line in output. Happens regardless of whether condition evaluates to true or false.

If statements at beginning of macro don't produce any blank lines.

## Template Code
```jinja
{# produces 3 lines of output #}
{% macro foo() %}
foofoo
{% if true %}
barbar
{% endif %}
{%- endmacro %}

{# produces 2 lines of output #}
{% macro foo2() %}
{% if true %}
bar2bar2
{% endif %}
foo2foo2
{%- endmacro %}



aaaaa
{{ foo() }}
aaaaa



bbbbb
{{ foo2() }}
bbbbb

```

## Full Traceback
```pytb



aaaaa
foofoo
barbar
    
aaaaa



bbbbb
bar2bar2
foo2foo2
bbbbb

```

## Your Environment
* Python version: 3.7.3
* Jinja version: 2.10.1

**Comment by jaydarius** [comment] 2019-05-06 19:53
We've discovered the minus sign (or whitespace strip operator), when appended to the beginning of the `if` control and prepended to the end of said control, will remove those blank lines:
```
{% macro foo() %}
foofoo
{% if true -%}
barbar
{%- endif %}
{%- endmacro %}
```
So you could use this for now, but I will continue research in the docs to determine an answer to this question: should this whitespace strip operator, when appended and prepended to the macro, apply the strips to controls inside the macro?
If yes, then as you expect, you would not need to apply the operator for that `if` control.

**Comment by jaydarius** [comment] 2019-05-06 20:53
> So you could use this for now, but I will continue research in the docs...

I haven't found a definitive stance.  Tell me if this "workaround" is good for you @adambousley

**Comment by adambousley** [comment] 2019-05-07 15:54
As far as I can tell, this only works when the if statement evaluates to true. When the if statement evaluates to false, the extra blank line is still present:

```
{% macro foo() %}
foofoo
{% if false -%}
barbar
{%- endif %}
{%- endmacro %}

aaaaa
{{ foo() }}
aaaaa
```

gives

```
aaaaa
foofoo

aaaaa
```

For my purposes I was able to work around the issue by adding "|trim" to all my macro calls, but obviously this wouldn't work if you actually wanted a specific amount of whitespace out of the macro...

**Comment by bkiu** [comment] 2019-05-07 18:08
I'll take a look at this. Working at Pycon 2019 Sprints.

**Comment by kevin-brown** [comment] 2019-05-14 12:48
Here's a rough and quick explanation of why this is occurring in your most recent example. I haven't looked into the original examples yet to determine how they are being parsed, but it's possible the logic might be similar.

```
{% macro foo() %}
foofoo
{% if false -%}
barbar
{%- endif %}
{%- endmacro %}
```

Gets parsed by the system and when whitespace is made more obvious, becomes

```
{% macro foo() %}\nfoofoo\n{% if false -%}\nbarbar\n{%- endif %}\n{%- endmacro %}
```

Which when whitespace stripping is applied, is equivalent to

```
{% macro foo() %}foofoo\n{% if false %}barbar{% endif %}{% endmacro %}
```

Note the extra `\n` after `foofoo`. This wouldn't be stripped by `trim_blocks` because it does not happen at the beginning or the end of a block, and it wouldn't be stripped by `lstrip_blocks` because it is not left padding for a block.

So when it's used in a template like

```
aaaaa
{{ foo() }}
aaaaa
```

It is equivalent to

```
aaaaa\nfoofoo\n\naaaaa
```

Which is where you are getting the additional whitespace from. You can fix this by stripping the whitespace from _before_ the `{% if %}` block by doing

```
{% macro foo() %}
foofoo
{%- if false -%}
barbar
{%- endif %}
{%- endmacro %}
```

Note the extra `-` operator at the beginning of the `{% if %}` block. This should strip the whitespace that occurs before it, up to the "foofoo" in the template, which is what you are looking for.

----

It's also important to note that the output appears to be correct when the statement evaluates to `true` because you are expecting the whitespace to be there in that case. It sounds like you are actually expecting to be using `{%- if %}` to get the extra whitespace when the statement is true (so the words are separated) but not have the additional whitespace when the statement is false.

**Comment by adambousley** [comment] 2019-05-14 20:39
In that case, you would end up with "foofoobarbar" on one line when the if statement evaluates to true.

However, your explanation led me to the following solution, which gives the result I am looking for in both cases:

```
{% macro foo() %}
foofoo
{%- if false %}

barbar
{%- endif %}
{%- endmacro %}

{% macro foo2() %}
foofoo
{%- if true %}

barbar
{%- endif %}
{%- endmacro %}


aaaaa
{{ foo() }}
aaaaa



bbbbb
{{ foo2() }}
bbbbb
```

It seems like the solution would be to trim the macros after if statements have been evaluated (thus removing the trailing newline automatically in both cases), but I have no idea how feasible that is.

**Comment by kevin-brown** [comment] 2019-05-16 02:07
I just did some testing with this using `Environment().compile(template_string, raw=True)` to see what the underlying Python looked like, and discovered that this is not a bug and it matches the docs.

----

The first template code:

```
{% macro foo() %}
foofoo
{% if true %}
barbar
{% endif %}
{%- endmacro %}
```

Is equivalent to

```
{% macro foo() %}\nfoofoo\n{% if true %}\nbarbar\n{% endif %}\n{%- endmacro %}
```

Which after the whitespace operators are applied is equivalent to

```
{% macro foo() %}\nfoofoo\n{% if true %}\nbarbar\n{% endif %}{% endmacro %}
```

And after `trim_blocks` is applied, is equivalent to

```
{% macro foo() %}foofoo\n{% if true %}barbar\n{% endif %}{% endmacro %}
```

Note that [`trim_blocks` only trims the first `\n`](http://jinja.pocoo.org/docs/2.10/api/#jinja2.Environment) following the opening block tag. This is one thing I assumed was different before, and then I read the docs again and was surprised.

So when this macro is used in the following template

```
aaaaa
{{ foo() }}
aaaaa
```

It's equivalent to

```
aaaaa\nfoofoo\nbarbar\n\naaaaa
```

Which is where the extra `\n` comes from. It's part of the `barbar\n` and can be stripped out by using `{%- endif %}` to close off the conditional.

----

The second template code

```
{% macro foo2() %}
{% if true %}
bar2bar2
{% endif %}
foo2foo2
{%- endmacro %}
```

Is equivalent to

```
{% macro foo2() %}{% if true %}bar2bar2\n{% endif %}foo2foo2{% endmacro %}
```

You'll notice that there isn't an extra `\n` after `foo2foo2` because it was stripped out by the whitespace operator on `{%- endmacro %}`.

**Comment by kevin-brown** [comment] 2019-05-20 22:35
Closing this off since this isn't a bug, according to how the parsing logic works. But if you want to submit a pull request that makes the docs clearer, we're happy to review it.

**Closed by kevin-brown** 2019-05-20 22:35 UTC
