### ISSUE TITLE
Invalid character substitution of string with \x85 (\u0085) 

### ISSUE THREAD

**Issue by erny** [pallets/jinja#1313] opened 2020-11-20 10:53 UTC
When expanding a template with strings that contain \x85, a new line character is inserted. En case of JavaScript, this results in errores.

How to reproduce:
```python
>>> import jinja2
>>> jinja2.Template('Hello\x85World').render()
'hello\nWorld'
```
Expected:
```
'hello\x85World'
```

Environment:

- Python version: 3.8.5
- Jinja version: 2.11.2

**Comment by erny** [comment] 2020-11-20 11:25
It seems that the the minified JS includes a polyfill for String.trim, String.trimStart, String.trimEnd which includes the string: \u200b\u0085\u180e (./internals/string-trim-forced.js), so:

      >>> jinja2.Template('\u200b\u0085\u180e').render()
      '\u200b\n\u180e'

This will produce invalid JS.

**Comment by davidism** [comment] 2020-11-20 13:52
Duplicate of #769

**Closed by davidism** 2020-11-20 13:52 UTC
