### ISSUE TITLE
Context.resolve does not find macros imported from libraries

### ISSUE THREAD

**Issue by pmalagon** [pallets/jinja#1336] opened 2021-01-25 11:09 UTC
Bug in jinja2 when executing macro inside an imported library. 
function in runtime.py:149 resolve_or_missing(context, key, missing=missing)
fails in looking for a macro with a compound name as lib.macro_name.

The example is using flask_admin, which allows to call jinja macros in column_formatter of a ModelView.
It includes a Product Model with three integer columns: Cost1, Cost2, Cost3, with the same value and different formatter:
- Cost1: formatter using jinja macro in library buglib.html, called using 'buglib.render_cost1'
- Cost2: formatter using jinja macro in master.html (no library), called using 'render_cost2'
- Cost3: formatter using python formatter, which returns a Markup object

Although they are all similar, Cost1 is not shown while Cost2 and Cost3 are.

The bug has been tracked down to function resolve_or_missing(context, key, missing=missing) in runtime.py:149
Flask_Admin calls method resolve of Context (runtime.py:222) with key 'buglib.render_cost1' and a valid Context.
It cannot find a macro for that key, because it is 'render_cost1' in Context.parent['buglib']

I recommend Cost3 for Flask_Admin users while the bug is not solved.
I propose a modification to solve the bug.

The modification proposed is to iteratively look for the elements stated in the macro path:

runtime.py:149

```patch
def resolve_or_missing(context, key, missing=missing):
    if key in context.vars:
        return context.vars[key]

-    if key in context.parent:
-        return context.parent[key]
+    l_key = key.split('.')
+    try:
+        f = context.parent[l_key[0]]
+        for k in l_key[1:]:
+            f = getattr(f, k)
+
+        return f
+    except:
+        pass

    return missing
```

To run this example:

1. Unzip file and go to folder containing run_server.py

    unzip jinja2_bug.zip .
    cd jinja2_bug

2. Create and activate a virtual environment::

    virtualenv env -p python3
    source env/bin/activate

3. Install requirements::

    pip install -r 'requirements.txt'

4. Run the application::

    python run_server.py

5. Got to web page::

    http://localhost:5000/admin/products

The first time you run this example, a sample sqlite database gets populated automatically. To start
with a fresh database: `rm examples/sqla/admin/sample_db.sqlite`, and then restart the application.

Environment:

- Python version: 3.7.4
- Jinja version: 2.11.2
 
[jinja2_bug.zip](https://github.com/pallets/jinja/files/5866119/jinja2_bug.zip)

**Comment by davidism** [comment] 2021-01-25 15:16
I appreciate you making an example, but please reduce this to a minimal example that only requires Jinja.

**Comment by pmalagon** [comment] 2021-01-25 18:50
Bug in jinja when executing macro inside an imported library. 
function in runtime.py:149 resolve_or_missing(context, key, missing=missing)
fails in looking for a macro with a compound name as lib.macro_name.

The example shows two scenario, with two macros, one in the template (render_cost1) and another in a library imported in the template (buglib.render_cost2)::

1. Macros called from template, statically. Both works

2. Macros called in runtime from python through a function called from the template. render_cost1 works but buglib.render_cost2 is not found.

Example:

    import jinja2
    loader = jinja2.DictLoader({
        'master.html':'''{% import 'buglib.html' as buglib with context %}
    {% macro render_cost1(cost) %}<span>{{ cost }} EUR</span>
    {% endmacro %}

    --- In template
    Cost1 is {{ render_cost1(10) }}
    Cost2 is {{ buglib.render_cost2(10) }}

    --- In runtime
    {{ format() }}''',
        'buglib.html':'''{% macro render_cost2(cost) %}<span>{{ cost }} EUR</span>
    {% endmacro %}'''})
    templateEnv = jinja2.Environment(loader=loader)
    template = templateEnv.get_template('master.html')

    cost1_formatter = 'render_cost1'
    cost2_formatter = 'buglib.render_cost2'

    formatters = [cost1_formatter, cost2_formatter]

    @jinja2.contextfunction
    def format(context):
        str = ""
        for i in formatters:
            m=context.resolve(i)

            try:
                str = '{}{} is {}\n'.format(str, i, m(10))
            except Exception as e:
                str = '{}{}\n'.format(str, e)

        return str

    templateEnv.globals.update(format=format)
    outputText = template.render()  # this is where to put args to the template renderer
    print(outputText)


The bug has been tracked down to function resolve_or_missing(context, key, missing=missing) in runtime.py:149
It cannot find a macro for that key, because it is just 'buglib' in context.vars (or context.parents), and it is looking for 'buglib.render_cost2'. It must be done step by step, splitting the key by '.'

The modification proposed is to iteratively look for the elements stated in the macro path:

    runtime.py:149
    def resolve_or_missing(context, key, missing=missing):
    -    if key in context.vars:
    -        return context.vars[key]
    -
    -    if key in context.parent:
    -        return context.parent[key]
    +    c_vars = [context.vars, context.parent]
    +    l_key = key.split('.')
    +    for c_var in c_vars:
    +        try:
    +            f = c_var[l_key[0]]
    +            for k in l_key[1:]:
    +                f = getattr(f, k)
    +
    +            return f
    +        except:
    +            pass

    return missing

**Comment by kevin-brown** [comment] 2022-05-02 23:10
I created a very minimal example which shows the problem:

```python
main_str = """
{% import 'library.html' as lib with context %}

{% macro embedded_macro() %}
embedded
{% endmacro %}
{{ "abc" | test_filter }}
"""
lib_str = """
{% macro imported_macro() %}
imported
{% endmacro %}
"""

from jinja2 import Environment, DictLoader, pass_context

loader = DictLoader({
    "main.html": main_str,
    "library.html": lib_str,
})
env = Environment(loader=loader)

@pass_context
def test_filter(context, value):
    internal = context.resolve("embedded_macro")
    external = context.resolve("lib.imported_macro")

    print(internal())
    print(external())

    return value

env.filters["test_filter"] = test_filter

template = env.get_template("main.html")

print(template.render())
```

**Comment by kevin-brown** [comment] 2022-05-02 23:15
After looking at how the resolver works within templates and what changes are required to get it to work here for this example, I'm not sure this is actually a bug. The templates perform the equivalent of this when performing the call to the macro:

```python
getattr(context.resolve("lib"), "imported_macro")()
```

Which is to say that it properly calls the method on the imported library. This is because the library itself is the thing being imported here, not necessarily all of the macros defined within the library. I claim this is not a bug as a result and propose that anyone looking to do this properly imports the library and then calls the macro on it within their helpers.

**Comment by davidism** [comment] 2022-05-07 18:58
I agree, this is not a bug. It comes down to defining what `context.resolve` does: it resolves a name directly in the context. It doesn't resolve a dotted name by doing further attribute access. If the `flask_admin.model.template.macro()` function wants to allow looking up names within namespaces, they should add something similar to the `split` code you proposed. Alternatively, you can import a specific macro rather than the entire namespace, so its name will be in the context.

**Closed by davidism** 2022-05-07 18:58 UTC
