### ISSUE TITLE
Documentation written towards Python 2

### ISSUE THREAD

**Issue by alexbuzzbee** [pallets/jinja#1100] opened 2019-11-07 14:35 UTC
The documentation still seems to be largely written towards Python 2, particularly in sections discussing the `str` and `unicode` types, which is a distinction that only exists in Python 2. With the end of PSF support for Python 2 quickly approaching (less than two months as I write this), Jinja should focus its documentation mainly for Python 3 users and include Python 2-specific differences as side notes, if Python 2 is to be supported at all.

**Comment by davidism** [comment] 2019-11-07 14:46
duplicate of pallets/meta#26

PRs welcome, but if you want to work on this, please be thorough rather than fixing only a few things at a time.

**Closed by davidism** 2019-11-07 14:46 UTC
