### ISSUE TITLE
Feature: Coverage support on templates

### ISSUE THREAD

**Issue by jccardonar** [pallets/jinja#962] opened 2019-03-19 22:08 UTC
Support of coverage on jinja2 would be useful for testing  projects that heavily rely on templates. As the [docs](http://jinja.pocoo.org/docs/2.10/faq/) state, templates might  contain some logic, and coverage support would provide the tools to make sure that the logic is correctly tested. 

There is https://github.com/MrSenko/coverage-jinja-plugin, but unfortunately it does not work well. 

This has also been  (sometimes indirectly) discussed in  #674  #673 #581 #408 . @atodorov had different ideas on #674 . 

I am not familiar with the internals of jinja2 enough to know if this is possible or not. So,  I am asking, could this be feasible?

**Comment by davidism** [comment] 2019-03-19 23:35
Yes, it's feasible. Some combination of the issues you linked would be needed. Closing this as a duplicate of those.

**Closed by davidism** 2019-03-19 23:35 UTC

**Comment by jccardonar** [comment] 2019-03-20 01:01
So, without understanding much, I see two approaches: Using get_corresponding_lineno, which from #673 seems to be a no go, but who knows the state now. The other is  using the debug approach mentioned in #674 . Which one makes more sense?
