### ISSUE TITLE
TemplateStream.dump() crash

### ISSUE THREAD

**Issue by mpaolini** [pallets/jinja#386] opened 2014-12-03 13:55 UTC
This is the traceback

```
 [...]
    stream.dump('ccc')
  File "xxx/virtual/lib/python2.7/site-packages/jinja2/environment.py", line 1133, in dump
    close = False
TypeError: writelines() argument must be a sequence of strings
```

**Comment by davidism** [comment] 2019-10-28 21:06
I can't reproduce this issue as described. Closing due to age.

**Closed by davidism** 2019-10-28 21:06 UTC
