### ISSUE TITLE
Jinja caches 2nd-level macros too aggressively

### ISSUE THREAD

**Issue by RichardCochrane** [pallets/jinja#742] opened 2017-07-12 07:24 UTC
## Expected Behavior
When using a template that calls a macro (let's call this a 1st-level macro) that calls another macro (2nd-level macro), changes to the template and macros should reflect immediately on rendering.

## Actual Behavior
Changes to the 2nd-level macro are not reflecting without first saving (even without any changes) either the template or 1st-level macro.

## Template Code
```jinja
From `dashboard.jinja2`:

    {% from '_widgets.jinja2' import widgets %}

    <div>
        ...
        {{ widgets(args) }}
        ....
    </div>

From _widgets.jinja2:

    {% from '_my_chart.jinja2' import my_chart %}
    
    {% macro widgets(args) -%}
        <div class="sv-section sv-section--mastery">
            {{ my_chart(args) }}
        </div>
    {%- endmacro %}

From _my_chart.jinja2:

    {% macro my_chart(args) -%}
        <div>
            <!-- Beautiful Chart Code -->
        </div>
    {%- endmacro %}

```

## Full Traceback
```pytb
No traceback - error is seen in unexpected caching.
```

## Your Environment
* Python version: 2.7.10
* Jinja version: 2.9.6
* pyramid-jinja2: 2.3.3

**Comment by ThiefMaster** [comment] 2017-07-12 07:26
Duplicate of #253?

**Comment by RichardCochrane** [comment] 2017-07-12 10:53
@ThiefMaster I think you're right. I did search the repo for dups and although that issue relates to imports and includes, the symptoms (and probable cause) of both do appear to be the same. Do I just close this off or should I add a reference to this issue on that issue (so that Macros are specific included in the problem definition)?

**Comment by Jossnaz** [comment] 2018-09-20 15:29
it would be awesome to see some progress, this bug has been lying around for 5 years, and it affects everyone developing with nested macros, which basically should be everyone developing with jinja.

**Comment by davidism** [comment] 2019-10-25 17:47
Duplicate of #253

**Closed by davidism** 2019-10-25 17:47 UTC
