### ISSUE TITLE
Docs have styling issues

### ISSUE THREAD

**Issue by invisibleroads** [pallets/jinja#1751] opened 2022-11-01 21:11 UTC
Jinja docs have styling issues. Maybe we can limit table of contents depth to 3 or 4 levels?

![Screenshot from 2022-11-01 17-04-13](https://user-images.githubusercontent.com/266668/199340820-fc93c42a-c774-4bb6-b896-7af8a1852634.png)

https://jinja.palletsprojects.com/en/3.1.x/api/#jinja2.Environment

**Comment by davidism** [comment] 2022-11-01 21:20
Duplicate of https://github.com/pallets/pallets-sphinx-themes/issues/64

**Closed by davidism** 2022-11-01 21:20 UTC
