### ISSUE TITLE
Template caching uses only template name, ignores path

### ISSUE THREAD

**Issue by radiantone** [pallets/jinja#741] opened 2017-07-10 19:55 UTC
Jinja2 now caches templates using the name of the template. If I have many templates located in different paths with the same name 'template.html' or something, then Jinja2 always returns the firsts one that was retrieved. This behavior differs from past versions. Now I must rename all my templates to different names, which breaks my design pattern.

---

## Expected Behavior
Templates should be cached based on full path to template. not just filename

## Actual Behavior
Only template name is used for caching and different templates in different paths with same filename are ignored after the first one is cached.

```

## Your Environment
* Python version:  2.7
* Jinja version: 2

**Comment by ThiefMaster** [comment] 2017-07-10 19:57
> * Jinja version: 2

That's not a jinja version...

**Comment by ThiefMaster** [comment] 2017-07-10 20:00
I just checked the code and it uses a *template* name. This does not mean *file* name. Can you shown an example where the problem you describe supposedly happens?

**Comment by radiantone** [comment] 2017-07-10 20:03
Hi,
  Thank you for quick response. So in my system, I have modules that I load at runtime. Each module is a directory with  module/view.html (template), module/view.json, module/view.js etc.

When the system loads all the modules, it updates the template path to the directory of each module and the rendering module puts itself first. This may seem out of the ordinary, but it allows me to do inheritance of views. Anyway, it used to work fine. but now whenever the first view.html is rendered, then that becomes the template returned regardless of the jinja path pointing to a different view.html in a different directory.

**Comment by radiantone** [comment] 2017-07-10 20:04
Regardless of my system design, Jinja should know the different between somedirA/view.html and somedirB/view.html. Currently, it does not.

**Comment by ThiefMaster** [comment] 2017-07-10 20:07
No, it shouldn't. Because to Jinja it doesn't matter where a template comes from - it could be the file system, a dict, or anything else. The template path (or "template name") in the environment, on the other hand, is something that does uniquely identify a template.

Right now it sounds like something like `env.get_template('foo')` may reference different templates depending on some other criteria. Sorry to say, but if that's what you are doing it's just wrong! Ping me in #pocoo on IRC if you want a suggestion on how to do something like this in a much saner way.

**Comment by radiantone** [comment] 2017-07-10 20:13
No. That's not the case. Let me clarify.

Let's say jinja.path is set to ['moduleA/','moduleB/'] directories.

moduleA/
    view.html
moduleB/
    view.html

I then ask jinja to render_template('view.html'). It renders moduleA/view.html

If later I want it to render moduleB/view.html, I always get back moduleA/view.html because it only sees "view.html" in the cache. Again, this worked as I expected it to before recent (month or so) releases.

Does this make more sense?

**Comment by ThiefMaster** [comment] 2017-07-10 20:22
OK, now I understand. I don't think that's really a supported usecase...

Why not use a custom loader based on PrefixLoader that gets the prefix to use from whatever code you have to determine the active module? Then it'd just dispatch to FileSystemLoaders pointing to the various module template folders.

**Comment by radiantone** [comment] 2017-07-10 20:27
The way my system is setup is that I am loading modules of my application using Flask blueprints. At load time, I don't know where or what templates those loaded blueprint modules might define. They are defined in a json descriptor, including the directory where these templates reside. Thus my app rebuilds the jinja paths on the fly to render views as layers. It's a beautiful system and worked fine before recent jinja changes. I would consider this use case in your future code updates. It's quite powerful.

For now, I just rename all my templates which breaks the "pattern" a bit but is not too cumbersome.
If at least jinja uses the path to the template (which it must have under the covers) in the cache id, then this problem goes away and jinja is a little smarter for it.

**Comment by davidism** [comment] 2017-07-10 20:29
Jinja templates are not necessarily files. We can't use the file path because some templates do not have file paths. That's an implementation detail of the individual loaders.

**Comment by davidism** [comment] 2017-07-10 20:31
Clear the cache if you want to modify what's available to `ChoiceLoader` after loading a template.

**Comment by radiantone** [comment] 2017-07-10 20:37
Ok, I see that templates are somethings not files, but given whatever kind of template is being accessed the cache can choose the most unique possible key for it. IF its a file, then the absolute path is easily had.

Is there a way to disable the cache? I already use a decorated cache on my flask routes. I don't need jinja also doing it. In fact, it creates a problem.

**Comment by davidism** [comment] 2017-07-10 21:01
Duplicate of #298 #153

**Closed by davidism** 2017-07-10 21:01 UTC

**Comment by radiantone** [comment] 2017-07-11 00:02
So is there a work around? I think those other tickets are related but not duplicates. This behavior changed recently. So my ticket was created due to this change. I will revert to older version of Jinja and document the change. But I think the general problem here is that template names do not uniquely define the template. That would force a single template namespace which is a bad design on systems. It would be similar to have one directory only in a filesystem and having to name every file different.
