### ISSUE TITLE
Importing Jinja2 fails with ImportError from markupsafe

### ISSUE THREAD

**Issue by valentin-iris** [pallets/jinja#1595] opened 2022-02-18 16:18 UTC
Environment:

- Python version: 3.8.12
- Jinja version: 2.11.3

**Comment by davidism** [comment] 2022-02-18 16:19
Duplicate of #1585 

You are using an unsupported version of Jinja, please update to the latest version if possible. Additionally, please read https://hynek.me/articles/semver-will-not-save-you/, then use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of these types of changes early.

**Closed by davidism** 2022-02-18 16:19 UTC
