### ISSUE TITLE
someobj|string[:16] no longer works

### ISSUE THREAD

**Issue by florentx** [pallets/jinja#2] opened 2010-10-19 21:30 UTC
This syntax used to work until 2.5.2:

```
{{ someobj|string[:16] }}
```

But it gives a syntax error in 2.5.3 and above.

**Comment by kevin-brown** [comment] 2019-05-07 15:57
Closing this off since it appears as though the recommended way of doing this is to wrap the expression in `()` before slicing it.

I can confirm that this issue still exists on 2.10.x though.

**Closed by kevin-brown** 2019-05-07 15:57 UTC
