### ISSUE TITLE
AttributeError: module 'jinja2.ext' has no attribute 'with_'

### ISSUE THREAD

**Issue by IEnglishBad** [pallets/jinja#1657] opened 2022-04-11 16:29 UTC
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/license_query/app.py", line 10, in <module>
    from license_query import commands, public, user, license, dependency
  File "/app/license_query/public/__init__.py", line 3, in <module>
    from . import views  # noqa
  File "/app/license_query/public/views.py", line 14, in <module>
    from license_query.extensions import login_manager
  File "/app/license_query/extensions.py", line 18, in <module>
    debug_toolbar = DebugToolbarExtension()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask_debugtoolbar/__init__.py", line 53, in __init__
    loader=PackageLoader(__name__, 'templates'))
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/jinja2/environment.py", line 363, in __init__
    self.extensions = load_extensions(self, extensions)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/jinja2/environment.py", line 117, in load_extensions
    extension = t.cast(t.Type["Extension"], import_string(extension))
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/jinja2/utils.py", line 149, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
AttributeError: module 'jinja2.ext' has no attribute 'with_'

I have started flask app with gunicorn. Then i got this error.

Sometime ago,I ran this program with Jinja version 3.0.3,it's ok. But not in 3.1.1.

Environment:

- Python version: 3.7
- Jinja version: 3.1.1

**Comment by davidism** [comment] 2022-04-11 16:47
Duplicate of https://github.com/pallets/jinja/issues/1627, both the `with` and `autoescape` extensions have not been needed for many years, were deprecated in 3.0, and removed in 3.1.

**Closed by davidism** 2022-04-11 16:47 UTC

**Comment by davidism** [comment] 2022-04-11 16:49
Duplicate of https://github.com/flask-debugtoolbar/flask-debugtoolbar/pull/157, upgrade Flask-DebugToolbar.
