### ISSUE TITLE
indent filter bypass Markup and enables escaping

### ISSUE THREAD

**Issue by QLiMBer** [pallets/jinja#940] opened 2019-02-02 23:04 UTC
## Expected/Actual Behavior
I need to add Java Scripts (loaded from a file to a string) into my html code and indent the whole block of inserted scripts.
Scripts are passed to a template using Markup() to disable escaping.

**EXPECTED**
When **Markup() and indent filter** used, **result** is **indented** and **not escaped**.

**ACTUAL**

When **Markup() and indent filter** used, **result** is **indented** (expected) but **escaped** (unexpected).

## Code
**Python**
*setting:*
```
env = Environment(
	loader = FileSystemLoader('web/templates'),
	autoescape = select_autoescape(['html', 'xml'])
)
template = env.get_template('index_template.html')```
```

*writing file:*
```
template.stream(
	google_scripts=Markup(google_scripts_string),
	last_update=last_update_string,
	table=Markup(video_html_table)
).dump('index.html')
```

**Template Code**
```jinja
{{ google_scripts|indent }}
```

## Full Traceback
```pytb
Paste the full traceback in case there is an exception

```

## Your Environment
* Python version: 3.7.1
* Jinja version: 2.10

**Comment by davidism** [comment] 2019-02-03 00:55
Duplicate of #823

**Closed by davidism** 2019-02-03 00:55 UTC
