### ISSUE TITLE
Support for pgettext

### ISSUE THREAD

**Issue by jorenham** [pallets/jinja#793] opened 2017-12-30 21:52 UTC
`jinja2.Environment.install_gettext_callables` only supports the `gettext` and `ngettext` *gettext* functions. I would like to use the `pgettext` (and `npgettext`) functions as well.

## Expected Behavior
Add context (using the *msgctxt* line) to a translatable string

## Actual Behavior
`pgettext` cannot be installed and throws an error when used

## Template Code
```jinja
{{ pgettext('month name', 'May') }}
```

## Full Traceback
```pytb
jinja2.exceptions.UndefinedError: 'pgettext' is undefined
```

## Your Environment
* Python version: 3.6
* Jinja version: 2.10

**Comment by davidism** [comment] 2018-11-20 17:55
Duplicate of #441

**Closed by davidism** 2018-11-20 17:55 UTC
