### ISSUE TITLE
Importing jinja2 fails with ImportError from MarkupSafe

### ISSUE THREAD

**Issue by valentin-iris** [pallets/jinja#1596] opened 2022-02-18 16:27 UTC
Importing Jinja 2.11.3 fails with `ImportError: cannot import name 'soft_unicode' from 'markupsafe'`

Steps to reproduce:
```
pip install jinja2==2.11.3 # comes with MarkupSafe-2.1.0 for me due to requirement MarkupSafe>=0.23
python -c "import jinja2"
```
from markupsafe 2.1.0 release notes:
Version 2.1.0
Released 2022-02-17

- Drop support for Python 3.6. [#262](https://github.com/pallets/markupsafe/pull/262)
- Remove soft_unicode, which was previously deprecated. Use soft_str instead. [#261](https://github.com/pallets/markupsafe/pull/261)
- Raise error on missing single placeholder during string interpolation. [#225](https://github.com/pallets/markupsafe/issues/225)
- Disable speedups module for GraalPython. [#277](https://github.com/pallets/markupsafe/issues/277)

so it seems usage of `soft_unicode` should be replaced with `soft_str`

Environment:

- Python version: 3.8.12
- Jinja version: 2.11.3

**Comment by davidism** [comment] 2022-02-18 16:28
Duplicate of #1585 

You are using an unsupported version of Jinja, please update to the latest version if possible. Additionally, please read https://hynek.me/articles/semver-will-not-save-you/, then use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of these types of changes early.

**Closed by davidism** 2022-02-18 16:28 UTC
