### ISSUE TITLE
Jinja set operation does not persist in for loop

### ISSUE THREAD

**Issue by ebmarquez** [pallets/jinja#901] opened 2018-09-24 21:25 UTC
---

## Expected Behavior
Tell us what should happen
Jinja==2.8
```
Start INDEX: 500
  500 remark "zero"
Remark INDEX: 510
INDEX End For: 520
  520 remark "One"
Remark INDEX: 530
INDEX End For: 540
  540 remark "Two"
Remark INDEX: 550
INDEX End For: 560
  560 remark "Three"
Remark INDEX: 570
INDEX End For: 580
  580 remark "Four"
Remark INDEX: 590
INDEX End For: 600
```

## Actual Behavior
Tell us what happens instead
jinja==2.10
```
Start INDEX: 500
  500 remark "zero"
Remark INDEX: 510
INDEX End For: 520
  500 remark "One"
Remark INDEX: 510
INDEX End For: 520
  500 remark "Two"
Remark INDEX: 510
INDEX End For: 520
  500 remark "Three"
Remark INDEX: 510
INDEX End For: 520
  500 remark "Four"
Remark INDEX: 510
INDEX End For: 520
```
## Template Code
**YAML Input**

```
ACLV2:
  "Test":
    LINE:
    - DESC: "zero"
    - DESC: "One"
    - DESC: "Two"
    - DESC: "Three"
    - DESC: "Four"
```
**Jinja Template**
```
{% if ACLV2 is defined %}
{% for key, value in ACLV2.iteritems() | sort() %}
{% set index = 500 %}
Start INDEX: {{ index }}
{% for acl in value['LINE'] %}
{% if acl['DESC'] is defined %}
  {{ index }} remark "{{ acl['DESC'] }}"
{% set index = (index + 10) %}
Remark INDEX: {{ index }}
{% endif %}
{% set index = (index + 10) %}
INDEX End For: {{ index }}
{% endfor %}
{% endfor %}
{% endif %}

```

## Full Traceback
no exceptions
```pytb
Paste the full traceback in case there is an exception

```

## Your Environment
* Python version: Python 2.7.12
* Jinja version:   Jinja2==2.10

**Comment by ThiefMaster** [comment] 2018-09-24 21:27
Duplicate of #641 - setting variables inside loops that persist outside a single iteration was never supposed to be a feature and just worked by accident. Since 2.10 there are a few enhancements that should provide workarounds for all cases that previously relied on this behavior.

**Closed by ThiefMaster** 2018-09-24 21:27 UTC
