### ISSUE TITLE
jinja2 2.8 environment cache retrieves wrong template, worked in jinja2 2.7

### ISSUE THREAD

**Issue by davidslac** [pallets/jinja#622] opened 2016-11-16 05:42 UTC
Some code that used to work in jinja2 2.7.2 (I think) is failing in 2.8. The code makes a template loader by deriving from FIleSystemLoader. The code stores multiple templates in one file using its own syntax to parse out separate template, ie, the template file may look like
```
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::template:::: A
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
hi from A
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

::::template:::: B
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
hi from B

```
The code uses syntax like:
`ji_env.get_template('templatefile.tmpl?A')
`
to load templates, so the loader treats the ? character special, and looks for special strings in the template file.

With version 2.8, when caching is on in the environment (the default), it seems that jinja2 is not caching templates via the whole name. If I load template A and then template B, when I try to render template B, I am getting template A - that is I think the caching is broken somehow - once I load template A from that file, I can't load any of the other templates..

Here is a small example of the problem - the file jinja_bug.py:
```
import sys
import os
import re
import jinja2 as ji

class TemplateLoader(ji.FileSystemLoader):
    def __init__(self):
        ji.FileSystemLoader.__init__(self, ['.'])

    def get_source(self, environment, template):
        fname, template = template.split('?')
        source, path, helper = ji.FileSystemLoader.get_source(self, environment, fname)

        # iterate over lines, find a template
        tmpl = []
        collect = False
        for line in source.splitlines(True):
            words = line.split()
            if words and words[0] == "::::template::::":
                if words[1] == template:
                    collect = True
                else:
                    collect = False
            elif line and line[0] == ':':
                pass
            elif collect: 
                tmpl.append(line)
        print ''.join(tmpl)
        print path
        print helper
        return ''.join(tmpl), path, helper

_jenv = ji.Environment(loader=TemplateLoader(),
                       trim_blocks=True,
                       line_statement_prefix='$', line_comment_prefix='$$')


def _TEMPL(template):
    return _jenv.get_template('templates.tmpl?'+template)

tmp = _TEMPL('enum_decl')
tmp = _TEMPL('ctor_decl_inline')
print tmp.render()

```
and here is the templates.tmpl file that it loads templates from:
```
:
:  Lines starting with colon are comments, except for special '::::template::::'
:
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::template:::: enum_decl
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:
:
{% if enum.comment %}

  /** {{enum.comment}} */
{% endif %}
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::template:::: ctor_decl_inline
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:
:
  {{classname}}({{arglist|join(", ")}})
$ if initlist:
    : {{initlist|join(", ")}}
$ endif
```
What should happen is that I render ctor_decl_inline. What in fact happens is that I get an error that  enum is not defined. If I don't first load the enum_decl template, then it works. This suggests that the ctor_decl_inline template is never loaded for its rendering.

**Comment by davidslac** [comment] 2017-01-06 17:14
Thank you for looking at this, I don't know jinjai well enough to answer the question. I am working around the issue by creating the _jenv variable as follows:

```
jiEnv = ji.Environment(loader=loader,
	                           cache_size=0,
	                           trim_blocks=True,
	                           line_statement_prefix='$',
	                           line_comment_prefix='$$')

```
so perhaps I am turning off all caching? 

The bug I reported is in code I did not develop myself, and it was developed a number of years ago. I think the pattern used, to derive from the FileSystemLoader, is an unusual thing to do today, however when I tried to redo it in a more straightforward way, I still got the same problem. It seems to me that even though the code uses names like

```
filename?templateA
filename?templateB

```
to distinguish templates, somehow jinja2 2.8 is not caching on those full names, just on the filename, whereas 2.7 worked. 

This was a really big issue for us. Back in Oct of 2015, I ran into this issue: https://jira.slac.stanford.edu/browse/PSRT-71, I upgraded jinja to 2.8, but a week later we ran into the bug and had to work fast to repair things. I put effort into unraveling our code (a complicated code generation package) to isolate the problem and gave up. A bigger effort more recently allowed me to isolate the problem. Anyways, thanks again for looking at this.  Would you like me to make a more straightforward example, without deriving from FileSystemLoader?

**Comment by amy-lei** [comment] 2020-06-23 16:38
Are you still experiencing this bug? I was thinking about looking into it 😃 but when I copied your code snippets, I couldn't reproduce the error

**Comment by davidism** [comment] 2020-06-23 17:26
Given the age of this ticket, the fact that the example is complex and admittedly not standard, and the fact that it's not reproducible, I'm going to close this. If this is still an issue, please open a new issue with a minimal example that demonstrates the issue with as simple an example as possible.

**Closed by davidism** 2020-06-23 17:26 UTC
