### ISSUE TITLE
Re-exports not listed in __all__

### ISSUE THREAD

**Issue by tomwatson1024** [pallets/jinja#1428] opened 2021-05-12 13:44 UTC
The `__init__.py` file at the root of the `jinja2` package does not define the `__all__` variable preventing that file's re-exports being picked up by some tooling.

See https://www.python.org/dev/peps/pep-0008/#id50, "Public and Internal Interfaces".

I hit this when setting mypy's `implicit_reexport` option to `False` - the stubs at https://github.com/python/typeshed/blob/master/stubs/Jinja2/jinja2/__init__.pyi do not define `__all__`, presumably because jinja2 itself does not.

Python 3.6.9
jinja2 3.0.0
mypy 0.800

**Comment by davidism** [comment] 2021-05-12 13:46
Duplicate of #1426

**Closed by davidism** 2021-05-12 13:46 UTC
