### ISSUE TITLE
sidebar in the 3.1.x docs is broken

### ISSUE THREAD

**Issue by minaminao** [pallets/jinja#1761] opened 2022-11-15 05:30 UTC
https://jinja.palletsprojects.com/en/3.1.x/api/

![image](https://user-images.githubusercontent.com/20497787/201833917-dc6efcfe-4340-4ca4-92f7-96af872c8924.png)

**Comment by davidism** [comment] 2022-11-15 06:01
Duplicate of https://github.com/pallets/pallets-sphinx-themes/issues/64

**Closed by davidism** 2022-11-15 06:01 UTC
