### ISSUE TITLE
with statement in call causes UnboundLocalError

### ISSUE THREAD

**Issue by dplepage** [pallets/jinja#118] opened 2012-04-23 19:05 UTC
I get `UnboundLocalError: local variable 'l_x' referenced before assignment` whenever I shadow a global via a `with` block inside a `call`:

``` jinja
{% set x = 1 %}
{% call foo() %}
    {% with x = 2 %}
    {% endwith %}
{% endcall %}
```

If I remove the first line, the problem goes away.

I'm using Jinja 2.6 and Python 2.6.7.

**Comment by hivre** [comment] 2015-03-01 13:58
most likely a duplicate of #278

**Comment by mitsuhiko** [comment] 2017-01-03 01:30
Fixed by #637

**Closed by mitsuhiko** 2017-01-03 01:30 UTC
