### ISSUE TITLE
Unicode NEL character is dropped

### ISSUE THREAD

**Issue by WaitF0r1t** [pallets/jinja#952] opened 2019-02-24 12:20 UTC
## Expected Behavior
When handling a template containing the [NEL character](https://www.charbase.com/0085-unicode-next-line-nel), I would expect the rendered result to still contain the character. Maybe I just missed to set an option when creating the template object.

## Actual Behavior
The NEL character is stripped from the rendered string.

## Minimum Example to Reproduce the Behavior
```python
from jinja2 import Template

input = '\x85'

template = Template(input)
output = template.render()

print(input)
print(input.encode('raw_unicode_escape'))
print(output)
print(output.encode('raw_unicode_escape'))
```
this produces
```

b'\x85'

b''
```
## Your Environment
* Python version: 3.7.2rc1
* Jinja version: 2.10

**Comment by crazymug** [comment] 2019-04-11 18:32
@WaitF0r1t current implementation of lexer changes NEL character to newline_sequence (Environment object parameter), as all line break characters, that mensioned in python docs https://docs.python.org/3/library/stdtypes.html#str.splitlines. 
The normalization of newlines is described here http://jinja.pocoo.org/docs/2.10/api/#unicode

There is although keep_trailing_newline parameter which not keeping and normalizing all possible Unicode newline chars (it only keeps '\r', '\r\n', '\n' and changes them to newline_sequence).

@davidism should it be fixed or it's just undocumented feature? I can make pull request.

**Comment by davidism** [comment] 2019-04-12 17:27
`keep_trailing_newline` has to do with the final newline in a document, not arbitrary newline characters within the document. I'm not sure what you're trying to say should be done in your comment.

**Comment by crazymug** [comment] 2019-04-12 17:54
I clearly understand the purpose of `keep_trailing_newline` parameter. Let me explain what i'm trying to say.
I ran this code:
```
from jinja2 import Template, Environment

input = '\x85\x01\x00\x85'

env = Environment(**keep_trailing_newline = False**)
template = env.from_string(input)

output = template.render()

print(input.encode('raw_unicode_escape'))
print(output.encode('raw_unicode_escape'))
```
and got this result:
```
b'\x85\x01\x00\x85'
b'\n\x01\x00'
```

I ran this code:
```
from jinja2 import Template, Environment

input = '\x85\x01\x00\x85'

env = Environment(**keep_trailing_newline = True**)
template = env.from_string(input)

output = template.render()

print(input.encode('raw_unicode_escape'))
print(output.encode('raw_unicode_escape'))
```
and got the same result:
```
b'\x85\x01\x00\x85'
b'\n\x01\x00'
```

As you can see, regardless to setting keep_trailing_newline to True or False, final NEL char is gone.
Is this expected behevior? Do you consider NEL char as newline char?

**Comment by ThiefMaster** [comment] 2019-04-12 17:55
I'm pretty sure we only consider `\n` a newline char.

**Comment by crazymug** [comment] 2019-04-12 18:05
@ThiefMaster as i see in https://github.com/pallets/jinja/blob/fd89fed7456e755e33ba70674c41be5ab222e193/jinja2/lexer.py#L605  keep_trailing_newline considers ('\r\n', '\r', '\n') as newline chars.

**Comment by crazymug** [comment] 2019-04-12 18:18
@davidism , @ThiefMaster I think it would be more clearly if documentation will state that keep_trailing_newline only keep one of the following chars: '\r\n', '\r', '\n'. Don't you think so?

**Comment by ThiefMaster** [comment] 2019-04-12 18:19
Is that needed? Do people really think of anything but \n/\r\n/\r when talking about newlines in a programming context?

**Comment by davidism** [comment] 2019-04-12 18:24
I guess it would also help to know under what circumstances @WaitF0r1t encountered that uncommon character, and why they needed it in the output. The example is almost too minimal, since it overlaps with the behavior of `keep_trailing_newline`.

**Comment by crazymug** [comment] 2019-04-12 18:28
@davidism I agree with you, let's wait for @WaitF0r1t comment

**Comment by WaitF0r1t** [comment] 2019-04-13 14:10
@davidism, @crazymug: From my point of view, the main question is whether any character (in this case NEL) in the original content should be converted to a different one or even removed from the output.
I found out about this potential problem when processing a JavaScript file, which was produced by webpack. A module used in the code contains a string constant with the NEL character in it. After processing this file with Jinja, the NEL character was replaced by a newline and the whole output got corrupted as the string constant now was spanning over two lines. I worked around this problem by preprocessing the file's contents and postprocessing the rendered output.
So in this case, the character did not appear at the end  of the content.
All in all, I would expect `input = 'some text\x85more text'` to produce unmodified output as well as `input = 'end of text\x85'`. So using `keep_trailing_newline` would not fix the original problem I had.

**Comment by crazymug** [comment] 2019-04-18 13:22
@WaitF0r1t  as I understand NEL char is very rare, its appeared in Unicode standard for backward compatibility with https://en.wikipedia.org/wiki/EBCDIC which is used in IBM's z/OS. As I stated above there are bunch of such newline chars, which jinja converts to widespread used chars. I think rare newline chars better be forgotten if you don't deal with rare, old hardware or software.
So it's very interesting case, can you provide more details, maybe more detailed task context? I think we can deside if your case is episodical or widespread only on basis of details you provide (couldn't find any other issues related to this one). This will lead to understanding of rationality of spending time to implement PR.

@davidism the task looks now like feature request, maybe we can add another parameter to Environment object initizialization after understanding that feature is rational?

**Comment by davidism** [comment] 2019-04-18 13:26
I don't want to add more config.

@WaitF0r1t I'm not clear why you were processing such a file with Jinja. I wouldn't expect it to be a valid Jinja template in the first place.

**Comment by WaitF0r1t** [comment] 2019-04-18 21:17
@davidism This would be a valid answer to my question. And as I already said, I was able to work around the issue. And I must admint that I was very surprised to find this character in my template. However, even if you only have HTML5 templates in your mind when using Jinja, wouldn't HTML5 also support UTF-8 encoding and thus allow using any valid unicode character? Why does Jinja transliterate e.g. NEL to `\n`? What is the reason behind this behavior?

**Comment by WaitF0r1t** [comment] 2019-04-18 21:21
@crazymug: I guess, this case is quite rare as one would expect from what you pointed out. Thus, I would be totally fine if it was pointed out in the documentation that several characters like NEL might be converted to ordinary newline characters during the template rendering process.

**Comment by davidism** [comment] 2019-04-18 21:25
Jinja is perfectly fine for generating JavaScript, I'm not saying it's only for HTML. But it makes no sense to take the output of Webpack and pass it to Jinja.

**Comment by WaitF0r1t** [comment] 2019-04-18 21:34
@davidism: Can you elaborate on why that does not make any sense? I am using Jinja in combination with flask to fill in several values in a pregenerated (static) JavaScript file for a certain request. The result is then used as the response.

**Comment by davidism** [comment] 2019-10-14 13:50
Duplicate of #769

**Closed by davidism** 2019-10-14 13:50 UTC
